services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_volume: