"""disabled

Revision ID: 3704eb78fbf9
Revises: cbe2146118ed
Create Date: 2024-10-08 19:42:37.408617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3704eb78fbf9'
down_revision: Union[str, None] = 'cbe2146118ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('disabled', sa.Boolean(), nullable=False), schema='rag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'disabled', schema='rag')
    # ### end Alembic commands ###
